### ISSUE TITLE
Use secret type SECRET_TYPE_MASTER_SEED with Subtype SECRET_SUBTYPE_BIP39 (0x01) 

### ISSUE THREAD

**Issue by Toporin** [Toporin/Seedkeeper-Android#16]
Use secret type SECRET_TYPE_MASTER_SEED with Subtype SECRET_SUBTYPE_BIP39 (0x01) by default for BIP39 mnemonic on v0.1 and v0.2.

Type SECRET_TYPE_BIP39_MNEMONIC is deprecated and should be only used to parse existing secret on cards set with the legacy desktop application

**Comment by psebic** [comment]
This is already done, implementation can be seen in this commit
https://github.com/Toporin/Seedkeeper-Android/pull/10/commits/8c73f3fa26686649a3d91195f613a3d9bc075e1c
