### ISSUE TITLE
[UI-Update] PIN setup is not UI friendly

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Seedkeeper-Android#56]
The current PIN UI (if I compare it to the iOS app) is too heavy !

![image](https://github.com/user-attachments/assets/0e1ff16e-6110-4169-a622-0a470435b6de)

I would suggest some improvment:

1) The very first title can be changed from "Saisir code PIN" to "Code PIN"
![image](https://github.com/user-attachments/assets/50314d07-b349-447a-927a-ce6ae58d7c9f)

2) The second title can be removed. It does not provide much more info than the main title
![image](https://github.com/user-attachments/assets/8da64a5f-8973-45bd-bc46-c5c38cabcb25)

3) Regarding the main text, I would rather prefer to use the appraoch on iOS and not put a big text. 
I would suggest to change the main text and just put: Entrez votre code PIN
(Watch out the translation in EN too !)
![image](https://github.com/user-attachments/assets/b6a9fdb1-d8b0-43cd-8cca-a74184622350)

4) Regarding the input PIN field, could you reduce the size of the text to make it on one line ?
![image](https://github.com/user-attachments/assets/9bd6a4c3-4be4-4437-ab02-237a3228d7bc)

Thank you.

**Comment by Toporin** [comment]
I think the title "Saisir code PIN" should be maintained as it provides important context for the user.
There are 3 different contexts for user PIN input:
* Enter (existing) PIN
* PIN setup (new PIN)
* Change PIN

For each of these 3 PIN, there may be additional screens steps, the context is provided by the subtitle: 
* for pin setup, user must confirm their PIN, 
* for change PIN, user must provide old pin first, then new pin, then confirm
* for enter PIN, if the card is actually not setup, user start by entering a (meaningless) PIN, then user enters the setup screen 

Consequently:
* the screent title indicates to user in which PIN operation they are, 
* the subtitle indicates which step of the current PIN operation they are (depending on the operation: enter pin, setup pin or change pin)
* a description provides more explanation

**Comment by Bastien-Satochip** [comment]
> I think the title "Saisir code PIN" should be maintained as it provides important context for the user. There are 3 different contexts for user PIN input:
> 
>     * Enter (existing) PIN
> 
>     * PIN setup (new PIN)
> 
>     * Change PIN
> 
> 
> For each of these 3 PIN, there may be additional screens steps, the context is provided by the subtitle:
> 
>     * for pin setup, user must confirm their PIN,
> 
>     * for change PIN, user must provide old pin first, then new pin, then confirm
> 
>     * for enter PIN, if the card is actually not setup, user start by entering a (meaningless) PIN, then user enters the setup screen
> 
> 
> Consequently:
> 
>     * the screent title indicates to user in which PIN operation they are,
> 
>     * the subtitle indicates which step of the current PIN operation they are (depending on the operation: enter pin, setup pin or change pin)
> 
>     * a description provides more explanation

Ok 👍
